server:
  port: 7891
  listen: "127.0.0.1"
  baseURL: "/_clv/browser"
  sources:
    - path: "${HOME}"
      config:
        defaultEnabled: true

database: "/opt/filebrowser/database.db"

auth:
  methods:
    noauth: true
    password:
      enabled: false
    proxy:
      enabled: true
      header: "X-Forwarded-User"
      createUser: true
