version: '3.8'
services:
  ai-studio:
    image: r.clv.zone/e2eorg/ai-studio:latest
    ports:
      - '22:22'
    volumes:
      - aistudiohome:/home
      - aistudiousr:/usr
      - aistudioopt:/opt
      - aistudiovar:/var
    x-clouve-metadata:
      containerName: ai-studio
      purpose: Frontend
      protocol: TCP
      isPublic: true
      memoryBase: 1
      cpuBase: 0.5
    x-clouve-healthcheck:
      enabled: false
      type: HTTP
      path: /health
      port: 22
      initialDelay: 30
      interval: 10
      timeout: 5
      failureThreshold: 3
      successThreshold: 1
    x-clouve-volumes:
      - name: aistudiohome
        size: 8
        description: 'Volume from Docker Compose for ai-studio-ai-studio (original: ai_studio_home)'
      - name: aistudiousr
        size: 8
        description: 'Volume from Docker Compose for ai-studio-ai-studio (original: ai_studio_usr)'
      - name: aistudioopt
        size: 8
        description: 'Volume from Docker Compose for ai-studio-ai-studio (original: ai_studio_opt)'
      - name: aistudiovar
        size: 8
        description: 'Volume from Docker Compose for ai-studio-ai-studio (original: ai_studio_var)'
volumes:
  aistudiohome:
    driver: local
  aistudiousr:
    driver: local
  aistudioopt:
    driver: local
  aistudiovar:
    driver: local
x-clouve-agent:
  enabled: true
  skills:
    url: https://github.com/Clouve/magneto-skills.git?plugins=ai-studio,mern#dynamic-port
    git:
      token: ''
      username: ''
  advanced:
    client: null
    passthroughEnv:
      CLV_SIDECAR_NAMESPACES: ai-studio
