version: '3.8'
services:
  ai-studio:
    image: ai-studio:latest
    ports:
      - '5173:5173'
    volumes:
      - aistudiohome:/home
      - aistudiousr:/usr
      - aistudioopt:/opt
      - aistudiovar:/var
    x-clouve-metadata:
      containerName: ai-studio
      purpose: Frontend
      protocol: TCP
      isPublic: true
      memoryBase: 2
      cpuBase: 0.5
    x-clouve-healthcheck:
      enabled: true
      type: TCP
      path: /
      port: 22
      initialDelay: 10
      interval: 10
      timeout: 5
      failureThreshold: 30
      successThreshold: 1
    healthcheck:
      test:
        - CMD
        - nc
        - '-z'
        - localhost
        - '22'
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 10s
    x-clouve-volumes:
      - name: aistudiohome
        size: 8
        description: 'Volume from Docker Compose for ai-studio-ai-studio (original: ai_studio_home)'
      - name: aistudiousr
        size: 8
        description: 'Volume from Docker Compose for ai-studio-ai-studio (original: ai_studio_usr)'
      - name: aistudioopt
        size: 8
        description: 'Volume from Docker Compose for ai-studio-ai-studio (original: ai_studio_opt)'
      - name: aistudiovar
        size: 8
        description: 'Volume from Docker Compose for ai-studio-ai-studio (original: ai_studio_var)'
volumes:
  aistudiohome:
    driver: local
  aistudiousr:
    driver: local
  aistudioopt:
    driver: local
  aistudiovar:
    driver: local
x-clouve-agent:
  enabled: true
  skills:
    url: https://github.com/Clouve/magneto-skills.git?plugins=ai-studio,mern#develop
    git:
      token: ''
      username: ''
  advanced:
    client: null
    passthroughEnv:
      CLV_SIDECAR_NAMESPACES: ai-studio
