#!/bin/bash
# Background helper that brings up sshd for the clouve-ops operator account.
#
# Designed to be backgrounded from this image's entrypoint:
#
#     /usr/local/bin/start-clouve-ops-sshd.sh &
#     exec "$@"
#
# Flow on each container start:
#   1. Generate sshd host keys if missing (ssh-keygen -A is idempotent).
#   2. Read the per-pod operator password from CLOUVE_OPS_PASSWORD (set
#      identically on this service, gibbon, and the Magneto Agent container
#      — hard-coded in dev compose, generated by Clouve as a `secret` in
#      prod). Apply it to the clouve-ops user via chpasswd.
#   3. Replace the script process with `sshd -D` so SSH is the only thing
#      running in this background tree — when the container's main process
#      (apache2-foreground / mysqld) exits, sshd is reaped along with it.
#
# Idempotent: re-running on container restart re-generates host keys
# (skipped if present), re-applies the same password, and re-execs sshd.
# No persistent state outside of /etc/ssh/ssh_host_*_key.

set -e

PREFIX="[clouve-ops-sshd]"

if [ -z "$CLOUVE_OPS_PASSWORD" ]; then
    echo "$PREFIX ✗ CLOUVE_OPS_PASSWORD is unset — sshd will not start" >&2
    exit 1
fi

echo "$PREFIX Generating sshd host keys if missing..."
ssh-keygen -A >/dev/null 2>&1

echo "$PREFIX Applying clouve-ops password from CLOUVE_OPS_PASSWORD"
echo "clouve-ops:$CLOUVE_OPS_PASSWORD" | chpasswd

mkdir -p /run/sshd
echo "$PREFIX Starting sshd (foreground in background tree)"
exec /usr/sbin/sshd -D
