# Symlink the Gibbon DevOps Skill into the user's Claude Code skill search path.
#
# The skill folder is mounted read-only at /clouve/skills/gibbon-devops/ at pod
# start. Claude Code only discovers user-scoped skills under ~/.claude/skills/,
# and $HOME is dynamic per tenant (derived from AI_STUDIO_USERNAME), so we
# bridge the static mount point and the dynamic home with a symlink created on
# the first login of each shell session.
#
# Sourced by AI Studio's /etc/profile.d/ mechanism (see chat/install.sh:60),
# which loads every *.sh drop-in at login. Mounted as a single-file bind from
# apps/gibbon/image/profile.d/clv-gibbon-skill.sh → /etc/profile.d/clv-gibbon-skill.sh.
#
# Idempotent: re-runs on every terminal open with no side effects if the link
# is already correct. Uses `ln -sfn` so a stale symlink from a previous skill
# version is transparently replaced.

if [ -d /clouve/skills/gibbon-devops ] && [ -n "$HOME" ]; then
    mkdir -p "$HOME/.claude/skills" 2>/dev/null
    ln -sfn /clouve/skills/gibbon-devops "$HOME/.claude/skills/gibbon-devops" 2>/dev/null
fi

# Install a per-user copy of the clouve-ops SSH identity key. The
# in-volume key at /clouve/ops-keys/id_ed25519 is generated by
# gibbon-ai-studio's entrypoint with mode 0644 so any shell user can
# bootstrap from it; ssh clients require identity files to be 0600 and
# owned by the user, so we materialise an owned copy in $HOME on the
# first interactive login of each shell session. Idempotent: skipped
# once $HOME/.ssh/clouve-ops exists.
if [ -s /clouve/ops-keys/id_ed25519 ] && [ -n "$HOME" ] && [ ! -s "$HOME/.ssh/clouve-ops" ]; then
    install -d -m 0700 "$HOME/.ssh" 2>/dev/null
    install -m 0600 /clouve/ops-keys/id_ed25519 "$HOME/.ssh/clouve-ops" 2>/dev/null
fi
